### ISSUE TITLE
Analytic functions not supported

### ISSUE THREAD

**Issue by jonghoonlee98** [google/zetasql#17]
I am trying to analyze a sql statement that include BigQuery functions `lag` and `lead` but am getting this error. Am I doing something wrong or is this not yet supported? I see that these functions exist in ZetaSQLFunction.java

```
16:20:29.885 [DEBUG] [TestEventLogger] zetasqltest > test FAILED
16:20:29.885 [DEBUG] [TestEventLogger]     com.google.zetasql.SqlException: Analytic functions not supported [at 6:8]
16:20:29.885 [DEBUG] [TestEventLogger]         at com.google.zetasql.Analyzer.analyzeStatement(Analyzer.java:60)
16:20:29.885 [DEBUG] [TestEventLogger]         at com.google.zetasql.Analyzer.analyzeStatement(Analyzer.java:46)
16:20:29.885 [DEBUG] [TestEventLogger]         at zetasqltest.test(zetasqltest.java:387)
16:20:29.885 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:20:29.885 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:20:29.885 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:20:29.885 [DEBUG] [TestEventLogger]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
16:20:29.885 [DEBUG] [TestEventLogger]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
16:20:29.885 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
16:20:29.885 [DEBUG] [TestEventLogger]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
16:20:29.885 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
16:20:29.885 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
16:20:29.886 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:20:29.886 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:20:29.886 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:20:29.886 [DEBUG] [TestEventLogger]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
16:20:29.886 [DEBUG] [TestEventLogger]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
16:20:29.886 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
16:20:29.886 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:20:29.886 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:20:29.886 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:20:29.886 [DEBUG] [TestEventLogger]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
16:20:29.887 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
16:20:29.887 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
16:20:29.887 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
16:20:29.887 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
16:20:29.887 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
16:20:29.887 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
16:20:29.887 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
16:20:29.887 [DEBUG] [TestEventLogger]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
16:20:29.887 [DEBUG] [TestEventLogger]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
16:20:29.887 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
16:20:29.887 [DEBUG] [TestEventLogger]         at java.base/java.lang.Thread.run(Thread.java:834)
16:20:29.887 [DEBUG] [TestEventLogger] 
16:20:29.887 [DEBUG] [TestEventLogger]         Caused by:
16:20:29.887 [DEBUG] [TestEventLogger]         com.google.zetasql.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Analytic functions not supported [at 6:8]
16:20:29.887 [DEBUG] [TestEventLogger]             at com.google.zetasql.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
16:20:29.887 [DEBUG] [TestEventLogger]             at com.google.zetasql.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
16:20:29.887 [DEBUG] [TestEventLogger]             at com.google.zetasql.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
16:20:29.887 [DEBUG] [TestEventLogger]             at com.google.zetasql.ZetaSqlLocalServiceGrpc$ZetaSqlLocalServiceBlockingStub.analyze(ZetaSqlLocalServiceGrpc.java:1063)
16:20:29.887 [DEBUG] [TestEventLogger]             at com.google.zetasql.Analyzer.analyzeStatement(Analyzer.java:58)
16:20:29.887 [DEBUG] [TestEventLogger]             ... 49 more
```

**Comment by matthewcbrown** [comment]
LAG and LEAD are supported, I believe you need to enable this language feature (FEATURE_ANALYTIC_FUNCTIONS)
See
https://github.com/google/zetasql/blob/109c7cdb95d7e16784e05a9293a87b129b5312fd/java/com/google/zetasql/LanguageOptions.java#L144

**Comment by jonghoonlee98** [comment]
@matthewcbrown 
FEATURE_ANALYTIC_FUNCTIONS is enabled (which I verified using `languageFeatureEnabled(LanguageFeature.FEATURE_ANALYTIC_FUNCTIONS)` but I am still getting the same error message. It didn't matter whether I used `enableMaximumLanguageFeatures()` or `enableLanguageFeature(LanguageFeature.FEATURE_ANALYTIC_FUNCTIONS)`

**Comment by matthewcbrown** [comment]
Not sure what's going, I can't reproduce anything like that, can you give me a minimal repro query?

**Comment by jonghoonlee98** [comment]
```
String sql = "select LAG(ch.oldvalue,1) OVER (PARTITION BY ch.id ORDER BY ch.createddate ASC) AS fieldprev FROM `warehouse.test.casehistory` ch";
String tableName = "warehouse.test.casehistory";
AnalyzerOptions options = new AnalyzerOptions();
SimpleCatalog catalog = new SimpleCatalog("test");
SimpleTable table = new SimpleTable(tableName);
LanguageOptions languageOptions = new LanguageOptions();
languageOptions.enableMaximumLanguageFeatures();
catalog.addZetaSQLFunctions(new ZetaSQLBuiltinFunctionOptions(languageOptions));
table.addSimpleColumn("createddate", TypeFactory.createSimpleType(TypeKind.TYPE_STRING));
table.addSimpleColumn("oldvalue", TypeFactory.createSimpleType(TypeKind.TYPE_STRING));
table.addSimpleColumn("id", TypeFactory.createSimpleType(TypeKind.TYPE_STRING));
catalog.addSimpleTable(table);
analyzeStatement(sql, options, catalog);
```
The sql statement runs fine in BigQuery

**Comment by matthewcbrown** [comment]
You are setting the language options on the catalog, but not on AnalyzerOptions, you need to add:
options.setLanguageOptions(languageOptions);

**Comment by jonghoonlee98** [comment]
That did it. Thanks!
