### ISSUE TITLE
StructType.toString throws UnsupportedOperationException

### ISSUE THREAD

**Issue by ibzib** [google/zetasql#24]
Doing String.format or any other function that calls toString fails on a struct type. 

```
java.lang.UnsupportedOperationException
	at com.google.zetasql.ZetaSQLStrings.toIdentifierLiteral(ZetaSQLStrings.java:39)
	at com.google.zetasql.StructType.debugString(StructType.java:177)
	at com.google.zetasql.Type.toString(Type.java:334)
	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2886)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2763)
	at java.util.Formatter.format(Formatter.java:2520)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2942)
```

**Comment by kanterov** [comment]
Our solution to the problem was overriding this class on the classpath with the version that has an implementation.

**Comment by ibzib** [comment]
Which version has an implementation?

**Comment by kanterov** [comment]
There nothing publicly available that I'm aware of, but such version could look like:
```java
public class ZetaSQLStrings {
...
  public static String toIdentifierLiteral(String str) {
    return str; // TODO escape if needed
  }
...
}
```
