### ISSUE TITLE
[BUG] "java.lang.IllegalStateException: No ZetaSQL ClientChannelProvider loaded."

### ISSUE THREAD

**Issue by roostapour** [google/zetasql#46]
Hi,

I am getting this error 
```
java.lang.IllegalStateException: No ZetaSQL ClientChannelProvider loaded.
 at com.google.zetasql.ClientChannelProvider.loadChannel(ClientChannelProvider.java:34)
 at com.google.zetasql.Client.getStub(Client.java:29)
 at com.google.zetasql.LanguageOptions.getDefaultFeatures(LanguageOptions.java:58)
 at com.google.zetasql.LanguageOptions.<init>(LanguageOptions.java:66)
 at com.google.zetasql.AnalyzerOptions.<init>(AnalyzerOptions.java:52)
 at com.google.zetasql.Analyzer.extractTableNamesFromStatement(Analyzer.java:183)
```

when running the following code 

```import com.google.zetasql.Analyzer;
private void testZeta(String query) {
   try {
       List<List<String>> tableNames = Analyzer.extractTableNamesFromStatement(query);
   } catch (Exception e) {
       logger.error(e.getMessage());
   }
}
```

My pom.xml is like this
```
<dependency>
  <groupId>com.google.zetasql</groupId>
  <artifactId>zetasql-client</artifactId>
  <version>2020.09.1</version>
</dependency>
<dependency>
  <groupId>com.google.zetasql</groupId>
  <artifactId>zetasql-jni-channel-darwin</artifactId>
  <version>2020.09.1</version>
</dependency>
```

I tried `zetasql-jni-channel` instead of `zetasql-jni-channel-darwin` and got the same error. I am running it on `Mac`. Any idea why I get this error and how I can solve it?
Does this work on `Macos`?

**Comment by roostapour** [comment]
I found the issue. Having both `zetasql-jni-channel` and `zetasql-client` in the `pom.xml` was the problem. 
I only included `zetasql-jni-channel` and now it is fixed. My `pom.xml` looks like this:
```
<dependency>
  <groupId>com.google.zetasql</groupId>
  <artifactId>zetasql-jni-channel</artifactId>
  <version>2020.09.1</version>
</dependency>
```
