### ISSUE TITLE
No matching signature for function CONCAT for argument types: STRING, INT64.

### ISSUE THREAD

**Issue by borjavb** [google/zetasql#65]
Hello!

I'm trying to parse the following query through the Java analyzer, but it looks like right now ZetalSQL syntax for CONCAT only supports:
- `CONCAT(STRING, [STRING, ...]) `
- `CONCAT(BYTES, [BYTES, ...])`
That seems to contradict the [documentation for concat](https://github.com/google/zetasql/blob/master/docs/functions-and-operators.md#concat)?

I have enabled all features through LanguageOptions, and a simple concat of strings is parsed correctly.
Is there a workaround to this issue, besides casting that int to a string?

Query:
```SQL
SELECT CONCAT('review_', 123),
FROM my_table
```

error
```
Caused by: com.google.zetasql.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: No matching signature for function CONCAT for argument types: STRING, INT64. Supported signatures: CONCAT(STRING, [STRING, ...]); CONCAT(BYTES, [BYTES, ...]) [at 14:32]
	at com.google.zetasql.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at com.google.zetasql.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at com.google.zetasql.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at com.google.zetasql.ZetaSqlLocalServiceGrpc$ZetaSqlLocalServiceBlockingStub.analyze(ZetaSqlLocalServiceGrpc.java:1002)
	at com.google.zetasql.Analyzer.analyzeNextStatement(Analyzer.java:204)
```

Thank you!

**Comment by borjavb** [comment]
And as soon as I wrote this I found the solution:
```Java
enableLanguageFeature(ZetaSQLOptions.LanguageFeature.FEATURE_V_1_3_CONCAT_MIXED_TYPES);
```
